version: "3.8"

services:
  arteditor-backend:
    build: ./backend
    container_name: arteditor-backend
    restart: unless-stopped
    volumes:
      - ./backend/temp_images:/app/temp_images
    expose:
      - "5001"
    environment:
      - FLASK_ENV=production
    networks:
      - arteditor-internal

  arteditor-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arteditor-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - arteditor-internal
      - caddy_network
    depends_on:
      - arteditor-backend

networks:
  caddy_network:
    external: true
  arteditor-internal:
    driver: bridge

